### ISSUE TITLE
Full shell support

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/distant#1]
`distant shell` would be the command to launch a connection to the remote machine. 

In terms of manipulating the local tty, we could use [crossterm](https://github.com/crossterm-rs/crossterm) or [termion](https://github.com/redox-os/termion), maybe? Not sure how to simulate the buffer on the other side where the programs are being run (like vim). Would need to look at mosh as an example.

**Comment by chipsenkbeil** [comment]
Maybe I can get away with a pty as seen through https://stackoverflow.com/questions/60367318/how-do-you-write-to-a-pty-master-rust and https://docs.rs/nix/0.22.0/nix/pty/index.html

**Comment by wez** [comment]
I'm biased on this, but I'd recommend my own set of crates, which are part of [wezterm](https://wezfurlong.org/wezterm/):

* https://docs.rs/portable-pty/0.4.0/portable_pty/
* https://docs.rs/termwiz/0.13.0/termwiz/

I can point you to an example of an interactive ssh client integrated into the `dev` CLI that we use at work

**Comment by chipsenkbeil** [comment]
Please and thank you :)

**Comment by chipsenkbeil** [comment]
> Maybe it's worth a considering integrating with https://github.com/zellij-org/zellij.
> 
> I have not personally switched to it yet, but it looks very promising. If nothing else it's a good resource to see and learn how they do, or plan to do, some things.

I'm not familiar with zellij. It's an interesting project, but it looks like their pty logic is baked into their own server, so not something I'd try to integrate into distant. Think I've got a plan laid out for tackling shell implementation. Just need to set aside some time to tackle it!
