### ISSUE TITLE
Panicking on for_each_mut_string

### ISSUE THREAD

**Issue by Polish-Civil** [chipsenkbeil/distant#141]
Hello, i've had an issue recently panicking on slice out of bounds, i think this line is the issue as it doesn't `check` this string value inside match statement before it's mutation. 

I do not have the logs as i just lost them ;/

https://github.com/chipsenkbeil/distant/blob/ea2e128bc4b8f96193972b9dbe70149eb2ba0675/distant-core/src/client/lsp/msg.rs#L304

**Comment by chipsenkbeil** [comment]
Hm, that call eventually triggers this: https://github.com/chipsenkbeil/distant/blob/ea2e128bc4b8f96193972b9dbe70149eb2ba0675/distant-core/src/client/lsp/msg.rs#L313

I'm not available to test it yet, but I think I meant to write `s.replace_range(pos..pos + old.len(), new);`.

**Comment by Polish-Civil** [comment]
oh yeah pos + old.len() should do it too :)

```
unable to swap prefix old: [file:] new: [distant:] string: [Expands to the file name in which it was invoked.\n\nWith [`line!`] and [`column!`], these macros provide debugging information for\ndevelopers about the location within the source.\n\nThe expanded expression has type `&'static str`, and the returned file\nis not the invocation of the `file!` macro itself, but rather the\nfirst macro invocation leading up to the invocation of the `file!`\nmacro.\n\n# Examples\n\n```rust\nlet this_file = file!();\nprintln!(\"defined in file: {this_file}\");]
```

Not sure what that gibberish is though, got it while running rust-analyzer

**Comment by chipsenkbeil** [comment]
Resolved by https://github.com/chipsenkbeil/distant/pull/146
