### ISSUE TITLE
Provide ARM binary

### ISSUE THREAD

**Issue by mdietrich16** [chipsenkbeil/distant#143]
I think that remote development for the Raspberry Pi exosystem is a big usecase for this project, but I sadly have not been able to compile a binary myself. I am probably just too stupid and inexperienced, but I could not get any distant binary to run on the Pi, regardless of which toolchain and target I compiled it with, aarch64-unknown-linux-gnu, aarch64-unknow-linux-musl, arm-unknown-linux-gnueabihf, ... Either it does not compile at all or the binary is rejected on the Pi. Anyways, that is not really anyones problem but mine, but an ARM binary would be really helpful for a lot of people I think.

**Comment by chipsenkbeil** [comment]
We've got an Apple ARM binary, so that instruction set works.

Can you provide more details when it comes to compilation issues and the binary being rejected on a Raspberry PI? Sounds like in one case you got it to compile, but the binary failed to run on the PI? I haven't tried to build with a target for a Raspberry PI, but I thought the target was `armv7-unknown-linux-gnueabihf`.

**Comment by chipsenkbeil** [comment]
The `ssh` support may also be a problem for ARM as the underlying C library for openssl may not compile (I don't know). That can be disabled, though.

**Comment by mdietrich16** [comment]
I had some time to compilation again today, with armv7-unknown-linux-gnueabihf as target. With arm-linux-gnueabihf-gcc as linker compilation of distant fails at the linking stage (I think?) with
```
error: linking with `arm-linux-gnueabihf-gcc` failed: exit status: 1
... (The used command)...
  = note: /usr/bin/arm-linux-gnueabihf-ld: cannot find -latomic: No such file or directory
          collect2: error: ld returned 1 exit status


error: could not compile `distant` due to previous error
```
With arm-none-linux-gnueabihf-gcc as linker it compiles successfully but after scp'ing it on to the Pi this happens:
```
max@Sydney:~ $ ls -la | grep distant
-rwxr-xr-x  1 max  max   18M 2022-11-02, 15:52:59   distant
max@Sydney:~ $ ./distant
bash: ./distant: No such file or directory
max@Sydney:~ $ bash ./distant
./distant: ./distant: cannot execute binary file
max@Sydney:~ $ file distant
distant: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, with debug_info, not stripped
max@Sydney:~ $
```

**Comment by chipsenkbeil** [comment]
@mdietrich16 with the release of [0.20.0-alpha.1](https://github.com/chipsenkbeil/distant/releases/tag/v0.20.0-alpha.1), we now offer a couple of different build options. I believe the one you want for a Raspberry PI is [distant-linux64-gnu-arm-v7](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0-alpha.1/distant-linux64-gnu-arm-v7).

I haven't run this on a Raspberry PI yet myself, but the target `armv7-unknown-linux-gnueabihf` used is supposed to be the one for the Raspberry PI to my knowledge.

**Comment by chipsenkbeil** [comment]
Closing this out as the new binaries should address the arm need on Linux, and also seems to have been confirmed that at least one of the new targets worked for the [Raspberry PI based on comments here](https://www.reddit.com/r/rust/comments/yibmgj/crosscompilation_from_arch_linux_x8664_to/).
