### ISSUE TITLE
Error when connecting from macos to Linux

### ISSUE THREAD

**Issue by fernandes** [chipsenkbeil/distant#161]
Opening this issue to start the conversation, I don't know exactly which information to send you here.

First, what project! This is really great and solve a real problem, can't wait to get it working on nvim 🧑‍💻 

So, here we go, I have two machines

Linux one 192.168.68.65
macos one 192.168.68.62

One Linux I started the manager:

```
⌁ distant manager listen --user --log-file /home/fernandes/distant.log --log-level trace
```

Then I tried to connect on macbook

```
distant client launch ssh://192.168.68.65
Failed to connect to manager

Caused by:
    0: Failed to connect to unix socket "/var/folders/41/g51hx5q90xqgk7wz9qv6738c0000gn/T/distant.sock"
    1: Failed to connect to unix socket "/var/folders/41/g51hx5q90xqgk7wz9qv6738c0000gn/T/fernandes.distant.sock"
    2: No such file or directory (os error 2)
```

I have no idea if the problem was on the macbook or linux, so I tried to estabilish a connection from linux

ps: running everything with normal user, no sudo/root involved

```
⌁ distant client launch ssh://192.168.68.65
SSH host 192.168.68.65:22 is not yet trusted.
Ecdsa256 Fingerprint: SHA256:7Ut28rDE1eL6WDU9MCKpMyjhWR7dr56oEG6ByTvKoA4.
Trust and continue connecting?
Enter [y/N]> 
y
3459643351

⌁ distant client action spawn -- echo 'Hello, this is from the other side'         
Hello, this is from the other side
```

and it worked! 🎉 

so I narrowed the investigation to the connection between mac and linux, the ssh between both is perfect, I use it for every day work. I don't know what extra information I could provide to debug it, please let me know.

Thank you again

**Comment by chipsenkbeil** [comment]
Ah! Sorry for the confusion and thanks for the report, @fernandes.

You run the manager on your local machine where you want to leverage distant. For the remote machine, you don't need to run anything as the manager facilitates spawning the server for you.

Check out an explanation of the architecture here! https://distant.rocks/documentation/architecture/

I'm hopping on a flight, so can't write too much of a response right now.

**Comment by fernandes** [comment]
oh, you're good @chipsenkbeil ! and you already wrote a lot on the site, I totally missed it 🤦‍♂️ lol

got the manager running on my local machine and 💥  it worked!

everything is working flawlessly, time to test with nvim! awesome!

closing the issue for now

have a safe flight! 🛫
