### ISSUE TITLE
distant fails to look up cache

### ISSUE THREAD

**Issue by westernwontons** [chipsenkbeil/distant#199]
Distant fails a cache lookup when executing command:

```bash
distant manager select
```

with the following error:

```bash
Failed to look up cache

Caused by:
    0: Failed to read cache from "/Users/.../Library/Caches/distant/cache.toml"
    1: TOML parse error at line 1, column 12
         |
       1 | selected = "10234354840777384061"
         |            ^^^^^^^^^^^^^^^^^^^^^^
       number too large to fit in target type
```

version:
﻿﻿﻿distant 0.20.0-alpha.8

**Comment by chipsenkbeil** [comment]
@westernwontons did you run an old version of distant in the past, by chance? That id looks bigger than an unsigned 32-bit integer, and an older version of distant previously used unsigned 64-bit integers.

**Comment by westernwontons** [comment]
Great, that solved it, thank you!
