### ISSUE TITLE
distant incorrectly determines that backslash may not be used in hostnames

### ISSUE THREAD

**Issue by philippejohns** [chipsenkbeil/distant#204]
similarly to #197 I am receiving an error when trying to connect with a backslash in my username as follows

`distant client launch ssh://orgname\\myname@servername`

where my username is orgname\myname - the second backslash is an escape character

**Comment by chipsenkbeil** [comment]
Hm, okay. I don't actually know what the allowed character range is for a username. I supposed I could take any character that is not @ or : and use that as the username.

**Comment by chipsenkbeil** [comment]
Resolved by https://github.com/chipsenkbeil/distant/commit/9096a7d81b16aada70a3d8f3ff2e78673bd19501.
