### ISSUE TITLE
Tailscale SSH: host key mismatch

### ISSUE THREAD

**Issue by viperML** [chipsenkbeil/distant#222]
When I try to `distant launch` on my remote server, I get the following error:

```
$ ssh shiva

[ayats@shiva:~]$ exit
logout
Connection to shiva closed.

$ ./distant launch ssh://shiva
Failed to launch server

Caused by:
    Fatal: host verification: host key mismatch for ssh server shiva:22.
    Got fingerprint SHA256:s0P68lmSjJRdKdfYEerWULJuZJSBPke5MJ1BavFMCG0 instead of expected value from known_hosts
    file /home/ayats/.ssh/known_hosts.
    Refusing to connect.
```

The SSH connection works fine if I call ssh directly. This might be related to using [Tailscale SSH](https://tailscale.com/kb/1193/tailscale-ssh), which might conflict with how distant handles SSH, but I don't know if that is the issue here.

**Comment by viperML** [comment]
Follow-up:

It seems like distant doesn't like my existing known_hosts. Wiping it and letting it generate it seems to work. Here are the differences of the two files:

```
# known_hosts generated by distant:
shiva ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLS7vPnY0Oz6hUnlM8tKYFrstB+mWVQEv5ud1BZtv2qcO+zeT+99DGosBs4Wn/9/KIySI0yKwbUVlgtcejiStz4= shiva:22
```

```
# known_hosts generated by plain ssh:
shiva ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJNXXwAs1vdR3V6wiO3Z6PqhayOq/vUFjrI+nvyVBrb0
```

**Comment by viperML** [comment]
👍

Should I close the issue?

**Comment by chipsenkbeil** [comment]
Sure, we can close it since you found a workaround.
