### ISSUE TITLE
distant-ssh DistantChannel low ability to write files concurrently

### ISSUE THREAD

**Issue by baoyachi** [chipsenkbeil/distant#227]
Concurrent write at the same time, limited to 8 count.

At present, it seems that the reason for this is：https://github.com/wez/wezterm/blob/main/wezterm-ssh/src/session.rs#L89-L90

```diff
impl Session {
    pub fn connect(config: ConfigMap) -> anyhow::Result<(Self, Receiver<SessionEvent>)> {
+        let (tx_event, rx_event) = bounded(8);
+        let (tx_req, rx_req) = bounded(8);
...
    }
)
```

**Comment by chipsenkbeil** [comment]
I can't control that. You'd need to file with @wez.

**Comment by chipsenkbeil** [comment]
Closing out as this is for a dependency and not distant itself.
