### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by anoduck** [chipsenkbeil/distant#231]
Went to install Distant on my Desktop, and received the `unrecognized OS type: OpenBSD` message. Rust is now commonplace on OpenBSD, and unless the software facilitates the use of native Linux network sockets (i.e. /proc/sys/net...), it should work. 

I will have to examine the install script to see if it can manually be installed and configured.

Just to clarify, you support SunOS and Windows, but not BSD? Wow...interesting...

**Comment by chipsenkbeil** [comment]
@anoduck hey there! Thanks for checking out the project. I tried building on both OpenBSD and NetBSD, but hit compilation errors. You can find the remnants of the attempt to productionize releases here: https://github.com/chipsenkbeil/distant/blob/master/.github/workflows/release.yml#L185-L244

> Just to clarify, you support SunOS and Windows, but not BSD? Wow...interesting...

Supported builds are in the releases section: https://github.com/chipsenkbeil/distant/releases/tag/v0.20.0

* [distant-aarch64-apple-darwin](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-aarch64-apple-darwin)
* [distant-aarch64-pc-windows-msvc.exe](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-aarch64-pc-windows-msvc.exe)
* [distant-aarch64-unknown-linux-gnu](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-aarch64-unknown-linux-gnu)
* [distant-aarch64-unknown-linux-musl](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-aarch64-unknown-linux-musl)
* [distant-armv7-unknown-linux-gnueabihf](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-armv7-unknown-linux-gnueabihf)
* [distant-universal-apple-darwin](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-universal-apple-darwin)
* [distant-x86_64-apple-darwin](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-apple-darwin)
* [distant-x86_64-pc-windows-msvc.exe](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-pc-windows-msvc.exe)
* [distant-x86_64-unknown-freebsd](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-unknown-freebsd)
* [distant-x86_64-unknown-linux-gnu](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-unknown-linux-gnu)
* [distant-x86_64-unknown-linux-musl](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-unknown-linux-musl)

As for not being able to build, the current issue is tied to the [OpenSSL Rust wrapper](https://github.com/sfackler/rust-openssl) being used to support ssh, which did not build on OpenBSD or NetBSD. Once we switch over to [russh](https://github.com/warp-tech/russh) (https://github.com/chipsenkbeil/distant/issues/193), a native implementation written in Rust, I believe the project should compile.

<img width="1035" alt="image" src="https://github.com/chipsenkbeil/distant/assets/2481802/2f659ba6-8a73-4fdd-b96c-ad6d26e9c808">

**Comment by chipsenkbeil** [comment]
You can find my comments trying to get builds running here: https://github.com/chipsenkbeil/distant/issues/150.

**Comment by anoduck** [comment]
OpenSSH is developed by OpenBSD, but yet OpenBSD provides it's own implementation of the library for the OS, and since so many things are based off of the "normal" OpenSSH implementation it makes life unnecessarily complicated for users like myself. 

@chipsenkbeil I have seen you around the hub before, and know your a good guy who works hard. There is no need to make things difficult for everyone. So, I am going to close this one out for now. If you ever need a user to test things out on OpenBSD and run the proverbial "hamster wheel", you only need to ask. Cheers, buddy.

**Comment by chipsenkbeil** [comment]
@anoduck sure thing! I do want to cover the BSDs at some point. The switch to russh should help with that. I'm not sure about the internal compiler error, but hoping that resolving the ssh library need will make good strides towards coverage.

Will reach out once there's a build possible.
