### ISSUE TITLE
GLIBC error?

### ISSUE THREAD

**Issue by drawnwren** [chipsenkbeil/distant#239]
I'm running archlinux with glibc = 2.3.8 locally. When I install and try to launch distant on ubuntu lts 20.04 (glibc version 2.3.1) I get the following exception: 

```
Caused by:
    Failed to spawn server: ''Last login: Wed Jan 31 20:17:51 2024 from 141.155.131.220
    distant server listen --daemon --host ssh

    (base) ]0;ubuntu@ip: ~[01;32mubuntu@ip-10-0-0-7[00m:[01;34m~[00m$ distant server listen --daemon --host ssh
    distant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32'\'' not found (required by distant)
    distant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33'\'' not found (required by distant)
    distant: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34'\'' not found (required by distant)
    (base) ]0;ubuntu@ip: ~[01;32mubuntu@ip[00m:[01;34m~[00m$
    (base) ]0;ubuntu@ip: ~[01;32mubuntu@ip[00m:[01;34m~[00m$ '
```

**Comment by chipsenkbeil** [comment]
distant 0.20.0 was compiled on a machine (via Github action) with a newer version of glibc than Ubuntu 20.04 has available. There's [a reference to the issue and generating new builds using older Linux](https://github.com/chipsenkbeil/distant/issues/186#issuecomment-1784185505).

In the meantime, you can:

1. switch on Ubuntu from the distant build using glibc to the build using musl, which should remove the glibc dependency issue you're running into. [musl release binary](https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-unknown-linux-musl)
2. compile distant on Ubuntu directly, which should then support that version of glibc
