### ISSUE TITLE
Support defaulting launch & proc-run to use $SHELL with option for --no-shell otherwise

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/distant#28]
At least for launch (proc-run may not be necessary), being able to take advantage of the path assigned to a user would be handy.

Testing with `ssh <host> echo '$SHELL'` resulted in the right shell being printed, so that environment variable is available. It looks like the majority of shells support `<shell> -l` for login and `<shell> -c <command>` to run a command as non-login. Doesn't look like you can run a login shell and execute a command, but I don't think a login shell is necessary to get the path configured for the specific user as non-login will still source files like `~/.bashrc` and others.

Anyway, idea here is to default to attempting to run distant over ssh using `$SHELL -c distant ...` to have appropriate environment variables established. If `--no-shell` is provided, then we wouldn't wrap in a `$SHELL` call.

Doing this for `proc-run` may not make sense as any environment given to the distant binary is passed on to its children; so, just providing launch with `$SHELL` should pass on the results to the children as well.

**Comment by chipsenkbeil** [comment]
It looks like we may actually need the login shell option. Bash, ksh, fish, and zsh support providing a login shell and command option together `<shell> -l -c env`. The shells `csh` and `tcsh` do not, but the [recommendation](https://stackoverflow.com/questions/32635599/tcsh-login-shell-with-command) is to do something like `echo ls | tcsh -l`.

So idea would be to do something like `echo 'distant ...' | $SHELL -l`

**Comment by chipsenkbeil** [comment]
Resolved by https://github.com/chipsenkbeil/distant/commit/160631bc7be3dc17d60bdcc3469c2f2b3f39dc63

**Comment by wez** [comment]
If you integrate libssh or libssh2, you can have the sshd give you a login shell by requesting a shell explicitly, and then you can send your commands on stdin, which is sort of in alignment with your comment above, but you shouldn't need to play around with `$SHELL` or figuring out how to spawn a login shell.

Also note that if you were in control of the spawning directly (which I know you're not in this case), spawning a login shell can be done this way in rust:

```rust
            let shell = Self::get_shell()?;
            let mut cmd = std::process::Command::new(&shell);
            // Run the shell as a login shell by prefixing the shell's
            // basename with `-` and setting that as argv0
            let basename = shell.rsplit('/').next().unwrap_or(&shell);
            cmd.arg0(&format!("-{}", basename));
```

https://github.com/wez/wezterm/blob/main/pty/src/cmdbuilder.rs#L190-L197

**Comment by wez** [comment]
FWIW, the `$SHELL -l` thing doesn't work with `fish`; I know because that's the technique I used to use in wezterm!

**Comment by chipsenkbeil** [comment]
Good call out about fish :) If I get to the point of incorporating an ssh
client and have the control you mentioned, I'd definitely switch to that!

For now, fish users would include `--no-shell`
