### ISSUE TITLE
Could not resolve hostname when doing 'distant launch'

### ISSUE THREAD

**Issue by allencho1222** [chipsenkbeil/distant#85]
__distant__ (v 0.15.0) fails to resolve hostname (IP) while followings are successfully done:

1. **DistantLaunch** from neovim
(`DistantLaunch 192.168.245.129 mode=distant distant.bin=/home/allencho122/local_installs/distant/distant<CR>`)

2. **ssh** to the target IP
(`ssh 192.168.245.129`)

However, within the terminal, `distant launch <IP> --distant /path/to/remote/distant` shows:
ERROR [distant] Exiting due to error: ssh: Could not resolve hostname 192.168.245.129:22: Name or service not known

**Comment by chipsenkbeil** [comment]
You're saying that **DistantLaunch** from neovim worked, sshing into `192.168.245.129` worked, but that using the terminal to launch failed?

**Comment by allencho1222** [comment]
Yes, it is. BTW this only happens on my desktop, while other PCs work correctly. I couldn't find causes.

**Comment by chipsenkbeil** [comment]
What operating system is your desktop? Do you have any custom ssh configs?

**Comment by allencho1222** [comment]
It uses ubuntu 18.04 and there are no differences in configurations between PCs.

**Comment by chipsenkbeil** [comment]
Oh, just saw that you're using v0.15.0 of the cli. Have you tried v0.15.1?

**Comment by allencho1222** [comment]
I also tried v0.15.1 and it didn't work. I think something is going wrong on my desktop because it cannot resolve the IP address of the virtual machine when using __distant__/

**Comment by chipsenkbeil** [comment]
The fact that the neovim library succeeded whereas the cli failed is perplexing. You're using which mode? Distant or ssh?

**Comment by allencho1222** [comment]
I sent you a video testing what I tried by your gmail. Please check it. It seems that only the distant mode does not work (Other PCs work correctly on distant mode).

**Comment by chipsenkbeil** [comment]
@allencho1222 I'm planning to close this issue soon due to lack of activity. I'm assuming you either got this working or moved on to another project, but I like to give heads up before closing an issue. Distant has changed quite a bit underneath including with the plugin, so this issue may be stale.
