### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by p00f** [chipsenkbeil/distant#92]
I downloaded the distant binary on the remote and put it on $PATH. Then
```
distant launch -i path/to/identity_file.pem -u user ec2-i-p-ad-dr.ap-south-1.compute.amazonaws.com
```
This commands exits 0. I can see that distant is running on the server by logging in via normal ssh and seeing `pidof distant`

The when I run `distant action system-info` locally, I get
```
ERROR [distant] Exiting due to error: No such file or directory (os error 2)
```

**Comment by chipsenkbeil** [comment]
@p00f what operating system are you using? Mac & Linux will attempt to spawn a local distant instance that listens on a unix domain socket. If for some reason that socket file is not found, you'll see that error.

You can try running `distant action --log-level trace system-info` and see what extra details it provides.

**Comment by p00f** [comment]
The server is running fedora, I'm running archlinux.
> Mac & Linux will attempt to spawn a local distant instance that listens on a unix domain socket. If for some reason that socket file is not found, you'll see that error

I don't understand, running `distant launch` locally spawned a distant instance on the server

> You can try running distant action --log-level trace system-info and see what extra details it provides.

I get the same error

**Comment by p00f** [comment]
Could this be because of permission issues (the socket file not being created)? The user I'm logging in as can't reboot
```
Failed to set wall message, ignoring: Interactive authentication required.
Failed to reboot system via logind: Interactive authentication required.
Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.
```

**Comment by chipsenkbeil** [comment]
@p00f there could be something related to the user you're logging into having issues. I'm not sure why some methods are hanging for you, though.

**Comment by chipsenkbeil** [comment]
@p00f I'm planning to close this issue soon as it seemed like it might have been more about the unix domain socket not being able to be created on your machine. Since there hasn't been any followup activity, I'm assuming you've moved on to another project (or got this working), but I like to give heads up before blindly closing!

**Comment by p00f** [comment]
Ye sure
